class RsaKeyResponse {
  String accessCode;
  String accountId;
  String cancelUrl;
  String cgst;
  String currency;
  String discountAmount;
  String igst;
  String merchantId;
  String orderId;
  String paymentGatewayUrl;
  String planId;
  String planName;
  String planDuration;
  String reason;
  double planRechargeAmount;
  String redirectUrl;
  String sgst;
  String status;
  double totalAmount;
  String transactionId;
  String workingKey;
  String rsaKey;
  String mobilePaymentPgwUrl;
  String addonPlanId;
  String addonPlanDuration;
  String addonPlanName;
  String addonPlanCost;
  String profileName;
  String cgstPercentage;
  String igstPercentage;
  String sgstPercentage;
  String paymentStateCode;
  String overDueAmount;

  RsaKeyResponse({
    required this.accessCode,
    required this.accountId,
    required this.cancelUrl,
    required this.cgst,
    required this.currency,
    required this.discountAmount,
    required this.igst,
    required this.merchantId,
    required this.orderId,
    required this.paymentGatewayUrl,
    required this.planId,
    required this.planName,
    required this.planDuration,
    required this.reason,
    required this.planRechargeAmount,
    required this.redirectUrl,
    required this.sgst,
    required this.status,
    required this.totalAmount,
    required this.transactionId,
    required this.workingKey,
    required this.rsaKey,
    required this.mobilePaymentPgwUrl,
    required this.addonPlanId,
    required this.addonPlanDuration,
    required this.addonPlanName,
    required this.addonPlanCost,
    required this.profileName,
    required this.cgstPercentage,
    required this.igstPercentage,
    required this.sgstPercentage,
    required this.paymentStateCode,
    required this.overDueAmount,
  });

  factory RsaKeyResponse.fromJson(Map<String, dynamic> json) {
    return RsaKeyResponse(
      accessCode: json['access_code'],
      accountId: json['account_id'],
      cancelUrl: json['cancel_url'],
      cgst: json['cgst'],
      currency: json['currency'],
      discountAmount: json['discount_amount'],
      igst: json['igst'],
      merchantId: json['merchant_id'],
      orderId: json['order_id'],
      paymentGatewayUrl: json['payment_gateway_url'],
      planId: json['plan_id'],
      planName: json['plan_name'],
      planDuration: json['plan_duration'],
      reason: json['reason'],
      planRechargeAmount: json['plan_recharge_amount'],
      redirectUrl: json['redirect_url'],
      sgst: json['sgst'],
      status: json['status'],
      totalAmount: json['total_amount'],
      transactionId: json['transaction_id'],
      workingKey: json['working_key'],
      rsaKey: json['rsa_key'],
      mobilePaymentPgwUrl: json['mobile_payment_pgw_url'],
      addonPlanId: json['addon_plan_id'],
      addonPlanDuration: json['addon_plan_duration'],
      addonPlanName: json['addon_plan_name'],
      addonPlanCost: json['addon_plan_cost'],
      profileName: json['profilename'],
      cgstPercentage: json['cgstpercentage'],
      igstPercentage: json['igstpercentage'],
      sgstPercentage: json['sgstpercentage'],
      paymentStateCode: json['payment_state_code'],
      overDueAmount: json['over_due_amount'],
    );
  }
}

